import os


OBSERVABILITY_LOG_FORMAT: str = os.getenv("OBSERVABILITY_LOG_FORMAT", "json")
OBSERVABILITY_LOG_LEVEL: str = os.getenv("OBSERVABILITY_LOG_LEVEL", "INFO")
OBSERVABILITY_METRICS_WINDOW_SECONDS: int = int(os.getenv("OBSERVABILITY_METRICS_WINDOW_SECONDS", "3600"))
OBSERVABILITY_HEALTH_STALE_SECONDS: int = int(os.getenv("OBSERVABILITY_HEALTH_STALE_SECONDS", "120"))
OBSERVABILITY_SERVICE_HEARTBEAT_SECONDS: int = int(os.getenv("OBSERVABILITY_SERVICE_HEARTBEAT_SECONDS", "60"))
OBSERVABILITY_MATCH_SCORE_STALE_SECONDS: int = int(os.getenv("OBSERVABILITY_MATCH_SCORE_STALE_SECONDS", "120"))
OBSERVABILITY_MATCH_ODDS_STALE_SECONDS: int = int(os.getenv("OBSERVABILITY_MATCH_ODDS_STALE_SECONDS", "60"))
OBSERVABILITY_TRACE_MAX_DEPTH: int = int(os.getenv("OBSERVABILITY_TRACE_MAX_DEPTH", "32"))
OBSERVABILITY_TELEGRAM_TIMEOUT_SECONDS: float = float(os.getenv("OBSERVABILITY_TELEGRAM_TIMEOUT_SECONDS", "10.0"))
